### ISSUE TITLE
Add 'ip in netblock' match

### ISSUE THREAD

**Issue by antoinet** [antoinet/intelmq#11]
In postgreSQL this looks like this:

 ... WHERE ip << netblock;

Example:
   '193.238.157.5' << '193.238.156.0/21'

**Comment by helderfernandes1279** [comment]
Hi Antoine,
I hope this email finds you well.

I remember to refer this feature while I was at the Hackhaton :D, do you
already have an idea about the implementation of this feature? I think
using the operator '<<' could be a good ideia, and then create a rule such
as this operator can only be used with specific key's, like source.ip and
destination.ip. I also think that the python lib 'ipaddress' would be
usefull for ipv4 and ipv6 validation.

I you want to share some tasks you can count on me.

Best Regards

2017-08-18 12:52 GMT+01:00 Antoine Neuenschwander <notifications@github.com>
:

**Comment by antoinet** [comment]
Yes, I'm currently working on it, and I also opted for the `ipaddress` python package. I'm not sure if we want to restrict it to IntelMQ keys `source.ip` and `destination.ip` though. Somebody could introduce a custom field which contains IP addresses. However, I implemented some extra error handling for the case that the value in the event is invalid. (in which case the rule does not match and a error log message is emitted).

**Comment by digihash** [comment]
We could say that we limit it to keys that have values with the "type": "IPAddress". Then you're sure an IP address is used but it's not limited to the standard keys in IntelMQ.

**Comment by helderfernandes1279** [comment]
Great, the purpose owas to ensure that user will not use that operator with
a key that contains values that are not IP addresses, I think your
sugestion fits perfectly.

2017-08-18 15:01 GMT+01:00 Kevin Holvoet <notifications@github.com>:

**Comment by antoinet** [comment]
Todo: restrict LHS to keys with type `IPAddress` (according to harmonization.conf)
