### ISSUE TITLE
Graceful error handling

### ISSUE THREAD

**Issue by antoinet** [antoinet/intelmq#12]
Add try-except blocks to catch errors in the rule processing. Emit meaningful error messages with the logger.

**Comment by antoinet** [comment]
I think this isn't necessary outside of our use-cases, since the BOT framework already provides error handling: https://github.com/antoinet/intelmq/blob/master/intelmq/lib/bot.py#L126

If a bot generates an exception, IntelMQ will make a trace of it, which can be analysed with the `intelmqdump` command. Let's see what Sebastian thinks about it.

For now, I'll leave the issue in the "to be discussed" column.

**Comment by wagner-certat** [comment]
Yes, the bot class catches all errors. Depending on the configuration of intelmq (can be set per-bot and globally), the event will either be processed again (wait-time and number of retries configurable) or just dumped. It also catches errors in init() which will cause the bot to stop the initialization.
Depending on the configuration a traceback will be logged or not.

What you may catch are e.g. parsing errors if you can give a more meaningful error message. But again, just raise ValueError.

**Comment by antoinet** [comment]
Thanks 👍  I looked at parsing errors in antoinet/intelmq#5: the parsing of the grammar file (part of the code) and the sieve file (provided by the user) are both in a try-except block. Corresponding log error messages with the reason and line and column numbers are emitted and initialization of the bot is interrupted.

**Comment by wagner-certat** [comment]
The changes in c9100b8b0c4e82683ca79d6dd784187609b762a1 look meaningful.
