### ISSUE TITLE
Call `validator.py` implicitly when `intelmq check` is called

### ISSUE THREAD

**Issue by antoinet** [antoinet/intelmq#20]
https://github.com/certtools/intelmq/pull/1083#discussion-diff-136086094R146

**Comment by wagner-certat** [comment]
It would be nice to have a validation function in the Bot's class which is called - if defined - by the check script automatically - for all bots.

I can do some work on this.

**Comment by wagner-certat** [comment]
I implemented this in branch call-bot-check, which you can merge into your branch, see PR certtools/intelmq#1091

**Comment by antoinet** [comment]
should I merge only the 3 commits from the PR, or the entire branch?

**Comment by wagner-certat** [comment]
Doesn't matter. I'd merge the branch, it's easier :)
